services:
  traefik:
    # The official v3 Traefik docker image
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80" # HTTP Port
      - "443:443" # HTTPS Port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.yml:/etc/traefik/traefik.yml:ro # Static Configuration
      - ${PWD}/acme.json:/acme.json:rw # For ACME Let's Encrypt
      # - ./provider:/provider:ro # Dynamic Configuration Files
      # - ./traefik.log:/traefik.log:rw
    env_file: ../env.shared
    environment:
      - TZ=Asia/Taipei
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.service=api@internal" # This line is important!!! (necessary)
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080"
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - net
networks:
  net:
    name: traefik-bridge
