entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: reverse-proxy # external network (manually create by docker network create ... command)
  ### file provider is for dynamic configurations
  ### you have to bind-mount it onto the docker container if you want to use it
  # file:
    # directory: "/provider"
    # watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: please.use.your@email.com
      storage: '/acme.json'
      httpChallenge:
        entryPoint: web

api:
  insecure: false
