entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: reverse-proxy # external network (manually create by docker network create ... command)
  #file:
    #directory: "/provider"
    #watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: q18131500@gs.ncku.edu.tw
      storage: '/acme.json'
      httpChallenge:
        entryPoint: web

api:
  insecure: true

# log:
  # filePath: "/traefik.log"
  # level: DEBUG
