services:
  watchtower:
    container_name: watchtower
    image: 'containrrr/watchtower:latest'
    command: --schedule "0 30 5 * * *" --label-enable
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
